package main.java.almadorada.test.unitarias.MocksProd;

import java.sql.*;

public class MockConnectionProductoCompleto extends MockConnectionProd {

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) {
        if (sql.contains("FROM categorias WHERE id =")) {
            return new MockPreparedStatementCategoriaExiste();
        }
        return super.prepareStatement(sql, autoGeneratedKeys);
    }

    @Override
    public PreparedStatement prepareStatement(String sql) {
        if (sql.contains("FROM categorias WHERE id =")) {
            return new MockPreparedStatementCategoriaExiste();
        }
        return super.prepareStatement(sql);
    }
}
